### ISSUE TITLE
`TextDocumentSyncKind` and `TextDocumentSyncOptions` defined twice in spec

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1519]
I got no response for https://github.com/microsoft/language-server-protocol/issues/1509#issuecomment-1171039730, so I'm making its own issue.

`TextDocumentSyncKind` and `TextDocumentSyncOptions` are defined twice in the published spec. Worse is that their definitions are different for each.

Only one of the  `TextDocumentSyncKind` also includes the `export type TextDocumentSyncKind = 0 | 1 | 2;`

Only one of the `TextDocumentSyncOptions` contain the properties `willSave`, `willSaveWaitUntil`, and `save`.

**Comment by dbaeumer** [comment]
Sorry missed that.

**Comment by dbaeumer** [comment]
Addressed by removing one of the TextDocumentSyncKind. TextDocumentSyncOptions shows up twice since it second is an extension of the first. The doc says before

> The final structure of the `TextDocumentSyncClientCapabilities` and the `TextDocumentSyncOptions` server options look like this

**Comment by KamasamaK** [comment]
Now that there's a proper meta model with only one defined, I think this is less of an issue. But I still don't understand what an "extension" means in this context. They are named the same and there is no `extends` being used. They're also using the same name for their linkableAnchor, so it's only linking to the one with fewer properties.

**Comment by dbaeumer** [comment]
It is a motivation thing in the spec. Simple defining `TextDocumentSyncOptions` in one go is hard to motivate. That is why the spec starts with a basic definition and then proposes the final one.

**Comment by KamasamaK** [comment]
I still don't understand, but it's not that big of a deal except for the duplicate `linkableAnchor`.
